#!/usr/bin/env python3
import sys
import json
import shlex

# clangd reads compile_commands.json (which is generated by CMake) and tries to
# use the same compiler flags as GCC, but it chokes on Xtensa-specific ones.

BAD_FLAGS = {
    "-mlongcalls",
    "-fno-tree-switch-conversion",
    "-fstrict-volatile-bitfields",
    "-fno-shrink-wrap",
    "-Wno-frame-address",
    "-Wno-format",
    "-Wno-old-style-declaration",
    "-Wno-volatile",
    "-Wno-unused-but-set-variable",
    "-Wno-psabi",
    "-Wno-error=deprecated-declarations",
    "--specs=nano.specs",
    "-fstack-protector",
}

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <raw-compile-commands.json> <clean-output.json>")
        sys.exit(1)

    raw_path, clean_path = sys.argv[1], sys.argv[2]

    with open(raw_path, "r") as f:
        commands = json.load(f)

    for entry in commands:
        if "command" in entry:
            entry["arguments"] = shlex.split(entry.pop("command"))
        entry["arguments"] = [arg for arg in entry["arguments"] if arg not in BAD_FLAGS]

    with open(clean_path, "w") as f:
        json.dump(commands, f, indent=2)

if __name__ == "__main__":
    main()
