#pragma once

#include <stdint.h>

#include "building_clock_model.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BUILDING_CLOCK_VALIDATION_NO_ITEM UINT16_MAX

typedef enum {
    BUILDING_CLOCK_PREVALIDATION_OK = 0,
    BUILDING_CLOCK_PREVALIDATION_NULL_WORLD,
    BUILDING_CLOCK_PREVALIDATION_COUNT_EXCEEDS_CAPACITY,
    BUILDING_CLOCK_PREVALIDATION_PROTECTED_REGION_INVALID,
    BUILDING_CLOCK_PREVALIDATION_PROTECTED_REGION_OVERLAP,
    BUILDING_CLOCK_PREVALIDATION_NAVIGATION_NOT_EMPTY,
    BUILDING_CLOCK_PREVALIDATION_PLATFORM_BOUNDS,
    BUILDING_CLOCK_PREVALIDATION_PLATFORM_TOO_SHORT,
    BUILDING_CLOCK_PREVALIDATION_PLATFORM_PROTECTED_REGION,
    BUILDING_CLOCK_PREVALIDATION_PLATFORM_OVERLAP,
    BUILDING_CLOCK_PREVALIDATION_SUPPORT_BOUNDS,
    BUILDING_CLOCK_PREVALIDATION_SUPPORT_PROTECTED_REGION,
    BUILDING_CLOCK_PREVALIDATION_SUPPORT_OVERLAP,
    BUILDING_CLOCK_PREVALIDATION_SUPPORT_RELATIONSHIP,
    BUILDING_CLOCK_PREVALIDATION_LADDER_BOUNDS,
    BUILDING_CLOCK_PREVALIDATION_LADDER_ENDPOINT,
    BUILDING_CLOCK_PREVALIDATION_LADDER_PROTECTED_REGION,
    BUILDING_CLOCK_PREVALIDATION_CRANE_GEOMETRY,
    BUILDING_CLOCK_PREVALIDATION_LIFT_GEOMETRY,
    BUILDING_CLOCK_PREVALIDATION_CART_ROUTE_GEOMETRY,
    BUILDING_CLOCK_PREVALIDATION_LOCATION_BOUNDS,
    BUILDING_CLOCK_PREVALIDATION_LOCATION_PROTECTED_REGION,
    BUILDING_CLOCK_PREVALIDATION_LOCATION_OVERLAP,
    BUILDING_CLOCK_PREVALIDATION_DEBRIS_FALL_SPACE,
    BUILDING_CLOCK_PREVALIDATION_SPAWN_GEOMETRY,
    BUILDING_CLOCK_PREVALIDATION_DIGIT_ACCESS_GEOMETRY,
    BUILDING_CLOCK_PREVALIDATION_TEMP_ATTACHMENT_GEOMETRY,
    BUILDING_CLOCK_PREVALIDATION_COMPOSITION_TOO_DENSE,
    BUILDING_CLOCK_PREVALIDATION_NEGATIVE_SPACE,
} building_clock_prevalidation_reason_t;

typedef struct {
    building_clock_prevalidation_reason_t reason;
    uint16_t item_index;
} building_clock_prevalidation_result_t;

typedef enum {
    BUILDING_CLOCK_COMPLETE_VALIDATION_OK = 0,
    BUILDING_CLOCK_COMPLETE_VALIDATION_NULL_WORLD,
    BUILDING_CLOCK_COMPLETE_VALIDATION_GRAPH_CAPACITY,
    BUILDING_CLOCK_COMPLETE_VALIDATION_GRAPH_EMPTY,
    BUILDING_CLOCK_COMPLETE_VALIDATION_NODE_REFERENCE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_NODE_SOURCE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_EDGE_REFERENCE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_EDGE_SOURCE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_EDGE_GEOMETRY,
    BUILDING_CLOCK_COMPLETE_VALIDATION_SPAWN_UNREACHABLE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_DEPOT_UNREACHABLE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_STAGING_UNREACHABLE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_DEBRIS_UNREACHABLE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_MACHINERY_UNREACHABLE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_DIGIT_ACCESS_UNREACHABLE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_DEBRIS_SERVICE_ROUTE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_CART_STOP_UNREACHABLE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_WAITING_POSITION,
    BUILDING_CLOCK_COMPLETE_VALIDATION_HAZARD_RETREAT,
    BUILDING_CLOCK_COMPLETE_VALIDATION_MATERIAL_DELIVERY,
    BUILDING_CLOCK_COMPLETE_VALIDATION_UPPER_CONSTRUCTION_ACCESS,
    BUILDING_CLOCK_COMPLETE_VALIDATION_CRANE_RANGE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_TEMP_STRUCTURE_ROUTE,
    BUILDING_CLOCK_COMPLETE_VALIDATION_DEBRIS_FOUNDATION_CONFLICT,
} building_clock_complete_validation_reason_t;

typedef struct {
    building_clock_complete_validation_reason_t reason;
    uint16_t item_index;
} building_clock_complete_validation_result_t;

building_clock_prevalidation_result_t building_clock_prevalidate_candidate(const building_clock_world_t* world);
const char* building_clock_prevalidation_reason_name(building_clock_prevalidation_reason_t reason);
building_clock_complete_validation_result_t building_clock_validate_complete(const building_clock_world_t* world);
const char* building_clock_complete_validation_reason_name(building_clock_complete_validation_reason_t reason);

#ifdef __cplusplus
}
#endif
